version: "3"

tasks:
  build-server:
    cmds:
      - go build app/main.go
  build-client:
    dir: client
    cmds:
      - yarn install
      - yarn build
  docker-build:
    deps: [build-client, build-server]
    cmds:
      - docker build -t ghcr.io/sonac/stravach/stravach:latest .
  run-server:
    cmds:
      - go run app/main.go
  run-client:
    dir: client
    cmds:
      - yarn dev
  test:
    cmds:
      - go test -v ./app/...
