version: "3"

tasks:
  build-server:
    cmds:
      - go build app/main.go
  build-client:
    dir: client
    cmds:
      - yarn build
  docker-build:
    deps: [build-client, build-server]
    cmds:
      - docker build -t ghcr.io/sonac/stravach/stravach:latest .
  
  test:
    cmds:
      - go test -v ./app/...
