// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	models "stravach/app/storage/models"

	mock "github.com/stretchr/testify/mock"

	strava "stravach/app/strava"
)

// Strava is an autogenerated mock type for the Strava type
type Strava struct {
	mock.Mock
}

// Authorize provides a mock function with given fields: accessCode
func (_m *Strava) Authorize(accessCode string) (*strava.AuthResp, error) {
	ret := _m.Called(accessCode)

	var r0 *strava.AuthResp
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*strava.AuthResp, error)); ok {
		return rf(accessCode)
	}
	if rf, ok := ret.Get(0).(func(string) *strava.AuthResp); ok {
		r0 = rf(accessCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*strava.AuthResp)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accessCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActivity provides a mock function with given fields: accessToken, activityId
func (_m *Strava) GetActivity(accessToken string, activityId int64) (*models.UserActivity, error) {
	ret := _m.Called(accessToken, activityId)

	var r0 *models.UserActivity
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int64) (*models.UserActivity, error)); ok {
		return rf(accessToken, activityId)
	}
	if rf, ok := ret.Get(0).(func(string, int64) *models.UserActivity); ok {
		r0 = rf(accessToken, activityId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserActivity)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int64) error); ok {
		r1 = rf(accessToken, activityId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshAccessToken provides a mock function with given fields: refreshToken
func (_m *Strava) RefreshAccessToken(refreshToken string) (*strava.AuthResp, error) {
	ret := _m.Called(refreshToken)

	var r0 *strava.AuthResp
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*strava.AuthResp, error)); ok {
		return rf(refreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) *strava.AuthResp); ok {
		r0 = rf(refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*strava.AuthResp)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewStrava interface {
	mock.TestingT
	Cleanup(func())
}

// NewStrava creates a new instance of Strava. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStrava(t mockConstructorTestingTNewStrava) *Strava {
	mock := &Strava{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
