name: test
on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v1
      - uses: actions/checkout@master
      - name: test
        run: task test
